### PR TITLE
bump k6 version to 0.51.0 and go version to 1.21

### PR DESCRIPTION
**Pull request by kempsterc**
* k6 version to 0.51.0
* go version to 1.21 in CI

### CODE REVIEW

**Comment by kempsterc** [comment]
@LeonAdato would you mind reviewing please?

**Comment by LeonAdato** [comment]
@kempsterc sorry for the delay. I'm traveling and speaking at events this week and probably won't be able to review until early next week.

**Comment by kempsterc** [comment]
Ah! Apologies. 
At least I know now :). Thank you kindly!
No rush at all. 
Just saw an opportunity to help

**Review by javaducky — APPROVED** [review]
@kempsterc appears good to me! Thanks!

**Comment by kempsterc** [comment]
> @kempsterc appears good to me! Thanks!
> 
> Verified using the following steps:
> 
> * Checkout branch using `gh pr checkout 11`
> * Build k6 with updated extension using `make`
> * Confirmed k6 version upgrade using `./k6 version`
> * Start a StatsD target of a Graphite server using the Docker Compose file, `docker compose up`
> * Executed test script with new binary using `./k6 run -o output-statsd examples/ramping-vus.js`
> * Confirmed in Graphite UI (http://localhost:80/) that updates were coming into the instance

I followed the steps above, before I pushed

**Comment by kempsterc** [comment]
@javaducky @LeonAdato can we merge this one please?
many thanks

**Comment by kempsterc** [comment]
@nicholaspshaw 
probably needs
https://github.com/LeonAdato/xk6-output-statsd/pull/12
then release

**Comment by LeonAdato** [comment]
I'm traveling home today but will review and merge tomorrow when I'm back at my desk.

Thank you for the help! ( And patience!)

**Pull request merged**
